### ISSUE TITLE
Andha bewakoof hai tu.

### ISSUE THREAD

**Issue by aryanmediratta** [zrthxn/trociety-brain#3]
Documntation dhang se padha karo. PLEASE. Ek hi kaam tha jaanu, woh bhi nahi kiye? 
lololol.

**Comment by AbhishekWG** [comment]
Aryan bro, this isn't the way to implement this!
Documentation of OpenAlpr has it all.
Node Js server is available too. We going to upload solution soon! 
This is useless.
